services:
  fastapi:
    build:
      context: .  # Set the build context to the root directory
      dockerfile: ./Backend_FastAPIs/Dockerfile  # FastAPI Dockerfile in Fast_API folder
    container_name: fastapi_container
    ports:
      - "8000:8000"
    env_file:
      - ./.env  # Pass the .env file located in the root directory at runtime
    volumes:
      - ./bigdata-8989-c84dd170777d.json:/app/bigdata-8989-c84dd170777d.json  # Mount the JSON file at runtime
    networks:
      - app-network

  streamlit:
    build:
      context: .  # Set the build context to the root directory
      dockerfile: ./Frontend_Streamlit/Dockerfile  # Streamlit Dockerfile in Streamlit_app folder
    container_name: streamlit_container
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    env_file:
      - ./.env  # Pass the .env file located in the root directory at runtime
    volumes:
      - ./bigdata-8989-c84dd170777d.json:/app/bigdata-8989-c84dd170777d.json  # Mount the JSON file at runtime
    networks:
      - app-network

networks:
  app-network:
    driver: bridge